#!/bin/bash

echo "Welcome to SAFEST STORAGE EVER!!!!!"
echo "Put/get?"
read cmd

echo "Token?"
read filename

if [ $cmd = "put" ]; then
    echo "Secret?"
    read flag
    echo $flag > storage/$filename
    echo "OK!"
elif [ $cmd = "get" ]; then
    echo "Your secret: $(cat storage/$filename)"
else
    echo "Bad command"
    exit 1
fi

